## Exercício
#### Dada uma matriz simétrica qualquer, escreva a sua transposta

In [1]:
m = [
    [3, 5, 7, 9],
    [5, 4, 2, 8],
    [7, 2, 6, 1],
    [9, 8, 1, 5],
]

In [2]:
def transpose_matrix(matrix:list)->list:
    """
    Recebe a lista multidimensional e verifica se é:
    1 - Quadratica 'len(matrix[-1]) == len(matrix)'
    2 - Retangular 'len(matrix[-1]) > len(matrix)'
    3 - Retangular 'len(matrix[-1]) < len(matrix)'
    Retorna a matriz transposta como list([[],...[]])
    """
    
    mt = []
    mt.append([[0] for i in range(len(matrix[-1]))])
    mt = mt[0]
    
    def matrix_final(i:int)->list:
        return mt[i][1:]   
    
    if len(matrix[-1]) == len(matrix):
        
        [mt[row].append(matrix[col][row]) \
         for row in range(len(matrix)) \
         for col in range(len(matrix[-1]))]
    
    elif len(matrix[-1]) > len(matrix):
        
        [mt[col].append(test2[row][col]) \
        for row in range(len(test2)) \
        for col in range(len(test2[-1]))]
        
    else:
        
        [mt[col].append(matrix[row][col]) \
         for col in range(len(matrix)-1) \
         for row in range(len(matrix[-1])+1)]
    
    return [matrix_final(i) \
     for i in range(len(mt))]

In [3]:
print(*m, sep='\n')

[3, 5, 7, 9]
[5, 4, 2, 8]
[7, 2, 6, 1]
[9, 8, 1, 5]


In [4]:
print(*[[f'R {row} ---> C {col}'] \
 for col in range(len(m)) \
 for row in range(len(m[-1]))],sep='\n')

['R 0 ---> C 0']
['R 1 ---> C 0']
['R 2 ---> C 0']
['R 3 ---> C 0']
['R 0 ---> C 1']
['R 1 ---> C 1']
['R 2 ---> C 1']
['R 3 ---> C 1']
['R 0 ---> C 2']
['R 1 ---> C 2']
['R 2 ---> C 2']
['R 3 ---> C 2']
['R 0 ---> C 3']
['R 1 ---> C 3']
['R 2 ---> C 3']
['R 3 ---> C 3']


In [5]:
#print(f'R {row} ---> C {col}'

print(*transpose_matrix(m), sep='\n')

[3, 5, 7, 9]
[5, 4, 2, 8]
[7, 2, 6, 1]
[9, 8, 1, 5]


In [6]:
valid = [m[0][::-1].copy(),
         m[1][::-1].copy(),
         m[2][::-1].copy(),
         m[3][::-1].copy()]

In [7]:
print(*valid, sep='\n')

[9, 7, 5, 3]
[8, 2, 4, 5]
[1, 6, 2, 7]
[5, 1, 8, 9]


In [8]:
print(*transpose_matrix(valid), sep='\n')

[9, 8, 1, 5]
[7, 2, 6, 1]
[5, 4, 2, 8]
[3, 5, 7, 9]


In [9]:
print(*m, sep='\n')

[3, 5, 7, 9]
[5, 4, 2, 8]
[7, 2, 6, 1]
[9, 8, 1, 5]


In [10]:
test = [[6,2],
       [0,4],
       [1,5]]
print(*test,sep='\n')

[6, 2]
[0, 4]
[1, 5]


In [11]:
print(*[[f'R {row} -----> C {col}'] \
      for col in range(len(test)) \
      for row in range(len(test[-1]))], sep='\n')

['R 0 -----> C 0']
['R 1 -----> C 0']
['R 0 -----> C 1']
['R 1 -----> C 1']
['R 0 -----> C 2']
['R 1 -----> C 2']


In [12]:
print(*transpose_matrix(test), sep='\n')

[6, 0, 1]
[2, 4, 5]


In [13]:
test2 = transpose_matrix(test)
print(*test2, sep='\n')

[6, 0, 1]
[2, 4, 5]


In [14]:
print(*[[f'R {row} -----> C {col}'] \
      for col in range(len(test2)) \
      for row in range(len(test2[-1]))], sep='\n')

['R 0 -----> C 0']
['R 1 -----> C 0']
['R 2 -----> C 0']
['R 0 -----> C 1']
['R 1 -----> C 1']
['R 2 -----> C 1']


In [15]:
print(*transpose_matrix(test2), sep='\n')

[6, 2]
[0, 4]
[1, 5]


## Numpy - Biblioteca matemática mais utilizada com Álgebra Linear (Vetores e Matrizes)

In [16]:
import numpy as np

#### Estruturas Unidimensionais

In [17]:
a1 = np.array(['Spark','Hadoop','Python','R'])

In [18]:
a1

array(['Spark', 'Hadoop', 'Python', 'R'], dtype='<U6')

### Arrays podem ter listas de tipos diferentes
#### Estruturas Bidimensionais

In [19]:
a2 = np.array([['Altura','Largura','Profundidade'],
               [42,78,10],[22,48,50]])

In [20]:
a2

array([['Altura', 'Largura', 'Profundidade'],
       ['42', '78', '10'],
       ['22', '48', '50']], dtype='<U12')

In [21]:
a3 = np.array([[10,20,30],[40,50,60]])

In [22]:
a3

array([[10, 20, 30],
       [40, 50, 60]])

In [23]:
# Tamanho do array
a1.shape, a2.shape

((4,), (3, 3))

In [24]:
# Dimensões do Array
a1.ndim, a2.ndim

(1, 2)

In [25]:
# O método max() não funciona em arrays de tipo heterogeneo
a3.max()

60

In [26]:
# Atributp
a2.ndim

2

### Método Arrange

In [27]:
array = np.arange(20)
array

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19])

In [28]:
array = np.arange(0,100,10)
array

array([ 0, 10, 20, 30, 40, 50, 60, 70, 80, 90])

### Criando estruturas de dados com linspace

In [29]:
# A diferença na utilização do linspace para o Arange é o último elemento
# No ARANGE determina o incremento e no LINSPACE o número de elementos

matriz = np.linspace(0, 10, 20)
matriz

array([ 0.        ,  0.52631579,  1.05263158,  1.57894737,  2.10526316,
        2.63157895,  3.15789474,  3.68421053,  4.21052632,  4.73684211,
        5.26315789,  5.78947368,  6.31578947,  6.84210526,  7.36842105,
        7.89473684,  8.42105263,  8.94736842,  9.47368421, 10.        ])

In [30]:
matriz = np.linspace(0, 10, 5)
matriz

array([ 0. ,  2.5,  5. ,  7.5, 10. ])

In [31]:
matriz = np.linspace(0, 5, 5)
matriz

array([0.  , 1.25, 2.5 , 3.75, 5.  ])

### Estruturas de Matrizes

In [32]:
# numpy.zeros
matriz = np.zeros((10,10))
matriz

array([[0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.]])

In [33]:
# numpy.ones
matriz = np.ones((2,3))
matriz

array([[1., 1., 1.],
       [1., 1., 1.]])

In [34]:
# numpy.eye - Produz uma matriz do tipo Identity
matriz = np.eye(10)
matriz

array([[1., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 1., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 1., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 1., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 1., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 1., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 1., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 1.]])

In [35]:
# numpy.diag - Produz uma matriz de Identidade
# com determinando os valores da diagonal
matriz = np.diag((2,4,6,7,9,12,35,47,27))
matriz

array([[ 2,  0,  0,  0,  0,  0,  0,  0,  0],
       [ 0,  4,  0,  0,  0,  0,  0,  0,  0],
       [ 0,  0,  6,  0,  0,  0,  0,  0,  0],
       [ 0,  0,  0,  7,  0,  0,  0,  0,  0],
       [ 0,  0,  0,  0,  9,  0,  0,  0,  0],
       [ 0,  0,  0,  0,  0, 12,  0,  0,  0],
       [ 0,  0,  0,  0,  0,  0, 35,  0,  0],
       [ 0,  0,  0,  0,  0,  0,  0, 47,  0],
       [ 0,  0,  0,  0,  0,  0,  0,  0, 27]])

In [36]:
matriz = np.empty_like((10,5))
matriz

array([         0, 1073741824])

In [37]:

matriz = np.empty((10,5))
matriz

array([[             nan,  4.94065646e-324,  2.96439388e-321,
         4.94065646e-324,  4.38730294e-321],
       [ 2.03060980e-321,  4.42682819e-321,  2.03060980e-321,
         3.71537366e-321,  2.03060980e-321],
       [ 4.40706556e-321,  2.03060980e-321,  5.03946959e-321,
        -5.43230923e-312,  4.98018171e-321],
       [ 2.03060980e-321,  4.52564132e-321,  2.03060980e-321,
         4.54540394e-321,  2.03060980e-321],
       [ 5.31614635e-321,  2.03060980e-321,  6.02760088e-321,
         2.03060980e-321,  6.58095440e-321],
       [ 2.03060980e-321,  6.02760088e-321, -1.08723971e-311,
         0.00000000e+000,  0.00000000e+000],
       [ 0.00000000e+000,  0.00000000e+000,  0.00000000e+000,
         0.00000000e+000,  0.00000000e+000],
       [ 0.00000000e+000,  0.00000000e+000,  0.00000000e+000,
         0.00000000e+000,  0.00000000e+000],
       [ 0.00000000e+000, -1.63047080e-311,  1.51058173e-311,
         3.16202013e-322,  0.00000000e+000],
       [ 0.00000000e+000,  0.00000000

### numpy.tile

In [38]:
np.tile(np.array([[1,2],[3,4],[5,6]]),3)

array([[1, 2, 1, 2, 1, 2],
       [3, 4, 3, 4, 3, 4],
       [5, 6, 5, 6, 5, 6]])

In [39]:
np.tile(np.array([[1,2],[3,4],[5,6]]),(3,6)) # Num de vezes do array na (vertical, horizontal)

array([[1, 2, 1, 2, 1, 2, 1, 2, 1, 2, 1, 2],
       [3, 4, 3, 4, 3, 4, 3, 4, 3, 4, 3, 4],
       [5, 6, 5, 6, 5, 6, 5, 6, 5, 6, 5, 6],
       [1, 2, 1, 2, 1, 2, 1, 2, 1, 2, 1, 2],
       [3, 4, 3, 4, 3, 4, 3, 4, 3, 4, 3, 4],
       [5, 6, 5, 6, 5, 6, 5, 6, 5, 6, 5, 6],
       [1, 2, 1, 2, 1, 2, 1, 2, 1, 2, 1, 2],
       [3, 4, 3, 4, 3, 4, 3, 4, 3, 4, 3, 4],
       [5, 6, 5, 6, 5, 6, 5, 6, 5, 6, 5, 6]])

### Tipagem de Dados

In [40]:
# Podemos passar um tipo para o Array por parâmetro
a = np.array([-10, 10, 20, 30], dtype = 'float')
a

array([-10.,  10.,  20.,  30.])

In [41]:
a.dtype

dtype('float64')

In [42]:
b = np.array([-10, 10, 20, 30])
b

array([-10,  10,  20,  30])

In [43]:
b.dtype

dtype('int32')

In [44]:
# Caso exita elementos diferentes,
# o Python irá tipar o array pelo tipo mais específico.
c = np.array([-10, 10.5, 20, 30])
c

array([-10. ,  10.5,  20. ,  30. ])

In [45]:
c.dtype

dtype('float64')

In [46]:
d = np.array(['Universidade','dos','Dados'])

In [47]:
d.dtype

dtype('<U12')

In [48]:
# Array do tipo boleano
e = np.array([False,True,False])
e

array([False,  True, False])

In [49]:
e.dtype

dtype('bool')

### Cast de Arrays

In [50]:
f = np.array([-9,10,20.7])
f.dtype

dtype('float64')

In [51]:
# CAST com a função astype()
f.astype(int)

array([-9, 10, 20])

### Criando Arrays com operadores aritméticos em tempo de execução

In [52]:
array = np.arange(0,5)
array

array([0, 1, 2, 3, 4])

In [53]:
array = np.arange(0,10)*10
array

array([ 0, 10, 20, 30, 40, 50, 60, 70, 80, 90])

In [54]:
array = np.arange(0,10)**2
array

array([ 0,  1,  4,  9, 16, 25, 36, 49, 64, 81], dtype=int32)

<table border="1">
    <th colspan='11'>Operações aritiméticas entre Arrays</th>
    <tr>
        <td>Array A</td><td>0</td><td>1</td><td>2</td><td>3</td><td>4</td><td>5</td><td>6</td><td>7</td><td>8</td><td>9</td>
    </tr>
    <tr>
        <td>Array B</td><td>1</td><td>2</td><td>3</td><td>4</td><td>5</td><td>6</td><td>7</td><td>8</td><td>9</td><td>10</td>
    </tr>
</table>

In [55]:
arrayA = np.arange(0,10)
arrayB = np.arange(0,10)+1

In [56]:
arrayA

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [57]:
arrayB

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [58]:
# Soma
arrayA + arrayB

array([ 1,  3,  5,  7,  9, 11, 13, 15, 17, 19])

In [59]:
# Subtração
arrayA - arrayB

array([-1, -1, -1, -1, -1, -1, -1, -1, -1, -1])

In [60]:
# Divisão
arrayA / arrayB

array([0.        , 0.5       , 0.66666667, 0.75      , 0.8       ,
       0.83333333, 0.85714286, 0.875     , 0.88888889, 0.9       ])

In [61]:
# Multiplicação
arrayA * arrayB

array([ 0,  2,  6, 12, 20, 30, 42, 56, 72, 90])

In [62]:
# Comparação de arrays
arrayA == arrayB

array([False, False, False, False, False, False, False, False, False,
       False])

In [63]:
arrayA > arrayB

array([False, False, False, False, False, False, False, False, False,
       False])

In [64]:
arrayA < arrayB

array([ True,  True,  True,  True,  True,  True,  True,  True,  True,
        True])

In [65]:
# Utilizando a tabela da verdade numpy.logical_and()
array1 = np.array([True,False,True,False])
array2 = np.array([True,True,True,False])
array3 = np.array([True,False,True,False])
np.logical_and(array1, array2, array3)

array([ True, False,  True, False])

In [66]:
# Utilizando a tabela da verdade numpy.logical_or()
array1 = np.array([True,False,True,False])
array2 = np.array([True,True,True,False])
array3 = np.array([True,False,True,False])
np.logical_or(array1, array2, array3)

array([ True,  True,  True, False])

### Arrays com tamanhos diferentes

In [67]:
A = np.array([1,2,3,4,5])
B = np.array([1,2,3])

In [68]:
# A + B Não é possível

In [69]:
# A * B Não é possível

### Dot Product

In [70]:
A = np.array([2,4,6])
B = np.array([2,2,2])

In [71]:
# Hadmard Product
A * B

array([ 4,  8, 12])

In [72]:
# Dot Product
print(np.dot(A,B))

24


In [73]:
A = np.array([3,7,10])
B = np.array([9,3,2])

In [74]:
A * B

array([27, 21, 20])

In [75]:
sum((A*B))

68

In [76]:
np.dot(A,B)

68

### Cópias de Arrays

In [77]:
A = np.arange(10)
A

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [78]:
B = A[5:]
B

array([5, 6, 7, 8, 9])

In [79]:
A[:]=0

In [80]:
B

array([0, 0, 0, 0, 0])

In [81]:
A = np.arange(10)
A

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [82]:
B = A[5:].copy()

In [83]:
B

array([5, 6, 7, 8, 9])

In [84]:
A[:] = 0
A

array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0])

In [85]:
B

array([5, 6, 7, 8, 9])

### Testando o tampo em Python

In [86]:
%lsmagic

Available line magics:
%alias  %alias_magic  %autoawait  %autocall  %automagic  %autosave  %bookmark  %cd  %clear  %cls  %colors  %conda  %config  %connect_info  %copy  %ddir  %debug  %dhist  %dirs  %doctest_mode  %echo  %ed  %edit  %env  %gui  %hist  %history  %killbgscripts  %ldir  %less  %load  %load_ext  %loadpy  %logoff  %logon  %logstart  %logstate  %logstop  %ls  %lsmagic  %macro  %magic  %matplotlib  %mkdir  %more  %notebook  %page  %pastebin  %pdb  %pdef  %pdoc  %pfile  %pinfo  %pinfo2  %pip  %popd  %pprint  %precision  %prun  %psearch  %psource  %pushd  %pwd  %pycat  %pylab  %qtconsole  %quickref  %recall  %rehashx  %reload_ext  %ren  %rep  %rerun  %reset  %reset_selective  %rmdir  %run  %save  %sc  %set_env  %store  %sx  %system  %tb  %time  %timeit  %unalias  %unload_ext  %who  %who_ls  %whos  %xdel  %xmode

Available cell magics:
%%!  %%HTML  %%SVG  %%bash  %%capture  %%cmd  %%debug  %%file  %%html  %%javascript  %%js  %%latex  %%markdown  %%perl  %%prun  %%pypy  %%python 

In [87]:
%timeit 3+1

12.5 ns ± 0.915 ns per loop (mean ± std. dev. of 7 runs, 100000000 loops each)


In [88]:
def soma(a,b):
    num1 = a
    num2 = b
    result = a + b
    return result

def soma_test_a(a,b):
    num1 = a
    num2 = b
    return num1 + num2

def soma_test(a,b):
    return a + b

In [89]:
%timeit soma(3,1)

170 ns ± 18.9 ns per loop (mean ± std. dev. of 7 runs, 10000000 loops each)


In [90]:
%timeit soma_test_a(3,1)

153 ns ± 18.5 ns per loop (mean ± std. dev. of 7 runs, 10000000 loops each)


In [91]:
%timeit soma_test(3,1)

142 ns ± 4.74 ns per loop (mean ± std. dev. of 7 runs, 10000000 loops each)


### Testando Arrays Numpy

In [92]:
%%timeit

a = []
for i in range(10000):
    a.append(i + 7)

1.11 ms ± 7.99 µs per loop (mean ± std. dev. of 7 runs, 1000 loops each)


In [93]:
%%timeit
a = [i+7 for i in range(10000)]

849 µs ± 75.3 µs per loop (mean ± std. dev. of 7 runs, 1000 loops each)


In [94]:
%%timeit
a = [7 + np.arange(10000)]

14.6 µs ± 72.5 ns per loop (mean ± std. dev. of 7 runs, 100000 loops each)


### Indexação de arrays Unidimensionais

In [95]:
a = [1,2,11,6,8,18,2]
array = np.array(a)
print(type(array))

<class 'numpy.ndarray'>


In [96]:
print(array.shape)

(7,)


In [97]:
array[0]

1

In [98]:
array[2]

11

In [99]:
print(array[1:5])

[ 2 11  6  8]


In [100]:
# Fatiando com passos de 2 em 2
print(array[1:5:2])

[2 6]


In [101]:
print(array[-7:-3])

[ 1  2 11  6]


In [102]:
print(array[3:])

[ 6  8 18  2]


In [103]:
print(a[:4])

[1, 2, 11, 6]


In [104]:
array[::-1]

array([ 2, 18,  8,  6, 11,  2,  1])

In [105]:
# Copiando um array por referência
b = array[:]
print(b)

[ 1  2 11  6  8 18  2]


In [106]:
array[2]

11

In [107]:
# Concatenando 2 arrays

x = np.array([2,6,8,4])
y = np.array([11,8,2])
z = np.concatenate([x,y])
print(z)

[ 2  6  8  4 11  8  2]


### Indexação de Arrays Multidimensionais

In [108]:
# Exercício
matriz = np.matrix([['Nome','Sexo','Nasc'],
                  ['Clara','f','12/12/14'],
                  ['João','m','24/03/60']])
print(*matriz,sep='\n')

[['Nome' 'Sexo' 'Nasc']]
[['Clara' 'f' '12/12/14']]
[['João' 'm' '24/03/60']]


In [109]:
print(*matriz[:2,1:],sep='\n')

[['Sexo' 'Nasc']]
[['f' '12/12/14']]


In [110]:
print(*matriz[:,:2],sep='\n')

[['Nome' 'Sexo']]
[['Clara' 'f']]
[['João' 'm']]


In [111]:
print(*matriz[2],sep='\n')

[['João' 'm' '24/03/60']]


## Operações com Arrays Multidimensionais

<table>
    <th colspan=5>Lembre-se - A notação é sempre LINHA - COLUNA</th>
    <tr>
        <td>1</td><td>2</td><td>3</td><td>4</td>
    </tr>
    <tr>
        <td>5</td><td>6</td><td>7</td><td>8</td>
    </tr>
    <tr>
        <td>10</td><td>20</td><td>30</td><td>40</td>
    </tr>
    <tr>
        <td>50</td><td>60</td><td>70</td><td>80</td>
    </tr>
</table>

In [112]:
A = [[1,	 2,	  3,	4],
    [ 5,	 6,	  7,	8],
    [10,	20,	 30,	40],
    [50,	60,	 70,	80]]

array = np.array(A)
print(array)

[[ 1  2  3  4]
 [ 5  6  7  8]
 [10 20 30 40]
 [50 60 70 80]]


In [113]:
array[0]

array([1, 2, 3, 4])

In [114]:
array[2]

array([10, 20, 30, 40])

In [115]:
array[0,-1]

4

In [116]:
array[0,0]=0
print(array)

[[ 0  2  3  4]
 [ 5  6  7  8]
 [10 20 30 40]
 [50 60 70 80]]


### Trabalhando com Intervalos

In [117]:
# Pegando os números centrais
print(array[1:3,1:3])

[[ 6  7]
 [20 30]]


In [118]:
array.shape

(4, 4)

In [119]:
print(array[
    int(array.shape[0]/2)-1:int(array.shape[0]/2)+1,
    int(array.shape[1]/2)-1:int(array.shape[1]/2)+1])

[[ 6  7]
 [20 30]]


In [120]:
(array.shape[0]/2)-1

1.0

In [121]:
# Pegando o intervalo 7, 8, 30, 40
print(array[:,-1])

[ 4  8 40 80]


In [122]:
print(array[-1,:])

[50 60 70 80]


In [123]:
A = np.array([[1,2],[3,4]])
B = np.array([[5,6]])
C = np.concatenate((A,B))

print(C)

[[1 2]
 [3 4]
 [5 6]]


In [124]:
print(*transpose_matrix(C),sep='\n')

[1, 3, 5]
[2, 4, 6]


In [125]:
# Matrizes são objetos Estritamente bidimensionais,
# o que torna mais fácil as operações aritiméticas

A = np.matrix([[1,2],[3,4]])
B = np.matrix([[5,3],[8,7]])

Z = np.array([
    [[2,6],[8,4]],
    [[2,6],[8,4]],
    [[2,6],[8,4]]
])

Y = np.array([2,6,8,4])

In [126]:
type(A)

numpy.matrix

In [127]:
type(B)

numpy.matrix

In [128]:
type(Z)

numpy.ndarray

In [129]:
type(Y)

numpy.ndarray

In [130]:
print(A)

[[1 2]
 [3 4]]


In [131]:
print(Z)

[[[2 6]
  [8 4]]

 [[2 6]
  [8 4]]

 [[2 6]
  [8 4]]]


In [132]:
print(Y)

[2 6 8 4]


In [133]:
Z.shape

(3, 2, 2)

In [134]:
Y.shape

(4,)

### Soma

In [135]:
print(A + B)

[[ 6  5]
 [11 11]]


In [136]:
print(B + 3)

[[ 8  6]
 [11 10]]


### Subtração

In [137]:
print(A - B)

[[-4 -1]
 [-5 -3]]


### Multiplicação

In [138]:
A = np.matrix([[1,2],[3,4]])
print(A)

[[1 2]
 [3 4]]


In [139]:
# Arrumação em "cruz"
print(A * A)

[[ 7 10]
 [15 22]]


In [140]:
# Multiplicação Indice a Indice
print(np.multiply(A,A))

[[ 1  4]
 [ 9 16]]


### Inversa

In [141]:
print(np.linalg.inv(A))

[[-2.   1. ]
 [ 1.5 -0.5]]


In [142]:
from numpy.linalg import inv

In [143]:
print(inv(A))

[[-2.   1. ]
 [ 1.5 -0.5]]


### Transposta

In [144]:
print(A.T)

[[1 3]
 [2 4]]


### Transposição e Reshaping de Arrays

In [145]:
A = np.array([[10,20,30],[40,50,60]])
A

array([[10, 20, 30],
       [40, 50, 60]])

In [146]:
A.T

array([[10, 40],
       [20, 50],
       [30, 60]])

In [147]:
np.transpose(A)

array([[10, 40],
       [20, 50],
       [30, 60]])

### Broadcasting

In [148]:
B = np.array([[100,200,300]])
B

array([[100, 200, 300]])

In [149]:
B.T

array([[100],
       [200],
       [300]])

In [150]:
B.T + B

array([[200, 300, 400],
       [300, 400, 500],
       [400, 500, 600]])

### Convertendo Matrizes em Arrays

In [151]:
A = np.array([np.arange(10,60,10), np.arange(100,150,10)])
A

array([[ 10,  20,  30,  40,  50],
       [100, 110, 120, 130, 140]])

In [152]:
A.shape

(2, 5)

In [153]:
A.ravel()

array([ 10,  20,  30,  40,  50, 100, 110, 120, 130, 140])

In [154]:
A.T.ravel()

array([ 10, 100,  20, 110,  30, 120,  40, 130,  50, 140])

### Operadores Lógicos

In [155]:
array = np.random.randint(1,10,size=(4,4))
array

array([[8, 8, 7, 7],
       [7, 5, 8, 2],
       [5, 6, 2, 7],
       [8, 6, 1, 4]])

In [156]:
np.any((array % 7) == 0)

True

In [157]:
np.all(array < 11)

True

### Reshaping

In [158]:
array = np.arange(1,16)
array

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15])

In [159]:
array.reshape(3,5)

array([[ 1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10],
       [11, 12, 13, 14, 15]])

### Ordenando o Array

In [160]:
array = np.array([[3,2],[10,-1]])
array

array([[ 3,  2],
       [10, -1]])

In [161]:
array.sort(axis=1)
array

array([[ 2,  3],
       [-1, 10]])

In [162]:
array = np.array([[3,2],[10,-1]])
array

array([[ 3,  2],
       [10, -1]])

In [163]:
array.sort(axis=0)
array

array([[ 3, -1],
       [10,  2]])